document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('a[href^="#"]').forEach(anchor=>{anchor.addEventListener('click',function(e){e.preventDefault();document.querySelector(this.getAttribute('href')).scrollIntoView({behavior:'smooth'})})});const navbar=document.querySelector('.navbar');window.addEventListener('scroll',()=>{if(window.scrollY>50){navbar.classList.add('scrolled')}else{navbar.classList.remove('scrolled')}});const observerOptions={threshold:0.3};const observer=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('animate')}})},observerOptions);document.querySelectorAll('.feature-card').forEach(card=>{observer.observe(card)});const form=document.querySelector('#contactForm');if(form){const inputs=form.querySelectorAll('input, textarea, select');inputs.forEach(input=>{input.addEventListener('input',function(){if(this.checkValidity()){this.classList.remove('is-invalid');this.classList.add('is-valid')}else{this.classList.remove('is-valid');this.classList.add('is-invalid')}})})}
const navbarToggler=document.querySelector('.navbar-toggler');const navbarCollapse=document.querySelector('.navbar-collapse');const backdrop=document.createElement('div');backdrop.className='navbar-backdrop';document.body.appendChild(backdrop);function toggleMenu(){if(navbarCollapse.classList.contains('show')){navbarCollapse.classList.remove('show');backdrop.classList.remove('show');document.body.style.overflow='';navbarToggler.classList.remove('active')}else{navbarCollapse.classList.add('show');backdrop.classList.add('show');document.body.style.overflow='hidden';navbarToggler.classList.add('active')}}
navbarToggler.addEventListener('click',function(e){e.stopPropagation();toggleMenu()});backdrop.addEventListener('click',toggleMenu);document.querySelectorAll('.nav-link').forEach(link=>{link.addEventListener('click',()=>{if(navbarCollapse.classList.contains('show')){toggleMenu()}})});document.addEventListener('click',function(e){if(navbarCollapse.classList.contains('show')&&!navbarCollapse.contains(e.target)&&!navbarToggler.contains(e.target)){toggleMenu()}});window.addEventListener('resize',function(){if(window.innerWidth>768&&navbarCollapse.classList.contains('show')){toggleMenu()}});let lastScroll=0;window.addEventListener('scroll',function(){const currentScroll=window.pageYOffset;if(currentScroll>lastScroll&&navbarCollapse.classList.contains('show')){toggleMenu()}
lastScroll=currentScroll});document.getElementById('inquiryType').addEventListener('change',function(){const packageSelect=document.querySelector('.package-select');if(this.value==='package'){packageSelect.style.display='block';document.getElementById('packageType').required=!0}else{packageSelect.style.display='none';document.getElementById('packageType').required=!1}})});function handleSubmit(event){event.preventDefault();const form=event.target;const submitBtn=form.querySelector('button[type="submit"]');submitBtn.disabled=!0;setTimeout(()=>{const alertDiv=document.createElement('div');alertDiv.className='alert alert-success';alertDiv.style.position='fixed';alertDiv.style.top='20px';alertDiv.style.left='50%';alertDiv.style.transform='translateX(-50%)';alertDiv.style.zIndex='9999';alertDiv.innerHTML=`
            <i class="fi fi-rs-check"></i>
            <strong>تم بنجاح!</strong> تم إرسال رسالتك وسنقوم بالرد عليك قريباً.
        `;document.body.appendChild(alertDiv);submitBtn.disabled=!1;form.reset();setTimeout(()=>{alertDiv.remove()},3000)},1000);return!1}
function showAlert(type,message){const alertDiv=document.createElement('div');alertDiv.className=`alert alert-${type} alert-dismissible fade show contact-alert`;alertDiv.innerHTML=`
        ${message}
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    `}
document.querySelectorAll('.nav-link').forEach(link=>{link.addEventListener('click',()=>{const navbarToggler=document.querySelector('.navbar-toggler');const navbarCollapse=document.querySelector('.navbar-collapse');if(navbarCollapse.classList.contains('show')){navbarToggler.classList.remove('active');navbarCollapse.classList.remove('show');document.querySelector('.navbar-backdrop').classList.remove('show')}})})